apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-shell
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: lijiawang/lijiawang:lijiawang
        env:
        - name: TARGET
          value: "Shell Sample v1"
